Bottom snap carousel
MC-Team-17/RayD pull request #21
Opened 2023-06-02 10:20 UTC by palant-dev

Change log:

- Created a reusable component for a Snap Carousel
- Created view for Snap Carousel
- Created a model for cloths
- Added assets for icons (should be always imported as 500x500 px for best results and fast implementation)
In the future will be easy to connect a specific type of cloth to the percentage of exposed skin thanks to the model.

https://github.com/MC-Team-17/RayD/assets/113528707/9120d329-747b-4e3d-b663-3201fc71f3f4

2023-06-05 09:15 UTC, yukim17 requested changes

2023-06-05 09:15 UTC, yukim17 commented on RayD/RayD/UI/MainView/Subviews/SnapCarouselView.swift
> +                clothsUpper.append(ExposedSkin(clothIcon: "upper\(index)"))
Maybe we can hardcode it somewhere?

2023-06-05 09:15 UTC, yukim17 commented on RayD/RayD/UI/Models/ExposedSkin.swift
> +    var clothIcon: String
For example hardcode it here as a static variable

2023-06-05 09:15 UTC, yukim17 commented on RayD/RayD/UI/MainView/Subviews/SnapCarouselView.swift
> +    @State var currentIndex: Int = 0
We need different indexes for carousels

2023-06-05 12:42 UTC, slavny11 approved these changes

2023-06-05 12:42 UTC, slavny11 approved these changes

2023-06-05 15:08 UTC, palant-dev commented on RayD/RayD/UI/MainView/Subviews/SnapCarouselView.swift
> +    @State var currentIndex: Int = 0
Done!

2023-06-05 15:08 UTC, palant-dev commented on RayD/RayD/UI/MainView/Subviews/SnapCarouselView.swift
> +                clothsUpper.append(ExposedSkin(clothIcon: "upper\(index)"))
Sure I think that we can edit this part when the guys finish the icon so we can associate also the values to the specific cloth

2023-06-05 15:16 UTC, palant-dev reviewed
Added a stored property to keep track of the exposed skin

2023-06-05 15:21 UTC, palant-dev commented on RayD/RayD/UI/Models/ExposedSkin.swift
> +    var clothIcon: String
Sorry I made a wrong correction now it should be working, try to pull the latest changes

2023-06-06 07:48 UTC, palant-dev reviewed
Added the arrays of cloths and fixed the carousel adding the slider for the head too

2023-06-06 14:19 UTC, merged