Weather kit and location integration
MC-Team-17/RayD pull request #24
Opened 2023-06-05 08:13 UTC by yukim17

2023-06-05 10:42 UTC, slavny11 requested changes
discussed already what to change

2023-06-05 10:42 UTC, slavny11 commented on RayD/RayD/UI/MainView/MainViewModel.swift
> +        buttonTap
peredelyvai

2023-06-05 10:56 UTC, yukim17 commented on RayD/RayD/UI/MainView/MainViewModel.swift
> +        buttonTap
done

2023-06-06 08:21 UTC, palant-dev approved these changes
Interesting solutions I will discuss with you about some stuff later

2023-06-06 15:28 UTC, merged