SettingsView
MC-Team-17/RayD pull request #37
Opened 2023-06-14 13:02 UTC by slavny11

Add settingsView and provisional views (ie MailCompose for modal and WebView for showing webpage inside app). Add function in SettingsView in order to manage all connections (settings, external website, mail).
MailComposer doesn't work yet. Needed to turn on one in developer account and signing and capabilities. Now it crash. I commented this function so far it's not super important.
AppStore warning shows up, but we don't have an app in appstore, so link after this doesn;t work.
We need to add infor about Vit D and new icon for Terms of use (we didn;t have this in figma).

Apart all limitations that I mentioned above I think we need to merge now into develop and I will fix this issues later. 

The main change that can affect another branches is NavigationalView in @main. I need one that we can make native transitions and NavLinks.

2023-06-14 13:04 UTC, slavny11 commented
I merged develop into this branch - the issue is only with NavigationalView inside @main. We need to fix it and later I'll manage all the other minor problems from the new branch.

2023-06-15 07:39 UTC, palant-dev requested changes
See comments

2023-06-15 07:39 UTC, palant-dev commented on RayD/RayD/Common/App/RayDApp.swift
> +            NavigationView {
Have you tried putting navigation view only to the stack in Main View? Why we need it in the onboarding. If it works with no issue I'm fine with this.

2023-06-15 07:39 UTC, palant-dev commented on RayD/RayD/UI/MainView/Subviews/SettingsView.swift
> +#warning("Need to add mail in capabilities. Now it crashes app")
May you add a .disabled to the button with decresed opacity just for not letting the user tap on it for now cause we don't know how much time we have in the next days

2023-06-15 07:39 UTC, palant-dev commented on RayD/RayD/UI/MainView/Subviews/SettingsView.swift
> +                Button {
Same here

2023-06-15 08:41 UTC, yukim17 approved these changes

2023-06-15 09:34 UTC, slavny11 commented on RayD/RayD/UI/MainView/Subviews/SettingsView.swift
> +#warning("Need to add mail in capabilities. Now it crashes app")
Agree. Added

2023-06-15 09:42 UTC, palant-dev approved these changes

2023-06-15 10:12 UTC, slavny11 commented on RayD/RayD/Common/App/RayDApp.swift
> +            NavigationView {
hello

2023-06-15 10:53 UTC, palant-dev approved these changes

2023-06-15 10:53 UTC, merged