Counter function
MC-Team-17/RayD pull request #7
Opened 2023-05-24 08:34 UTC by GabriellAnnunziata

2023-05-24 10:16 UTC, slavny11 approved these changes

2023-05-25 08:35 UTC, yukim17 commented on RayD/VitDTimeTracker.swift
> +class VitDTimeTracker: ObservableObject {
Good practice to put `final` keyword before `
class VitDTimeTracker..` if you are sure that you are not going to use inheritance for this class.

2023-05-25 14:15 UTC, palant-dev requested changes
Check the comments, maybe we could improve even more the functions. But great job, a lot of stuff!

2023-05-25 14:15 UTC, palant-dev commented on RayD/VitDTimeTracker.swift
> +    func vitDCalculator (prodPerSeconds: Double, time: Int, todayVitD: Double, vitDSuggested: Double) {
maybe we could remove prodPerSeconds and vitDSuggested if we are using the stored property inside the class accessing it with "self". Read the following comments for better clarity.

2023-05-25 14:15 UTC, palant-dev commented on RayD/VitDTimeTracker.swift
> +    func checkReachedGoal (todayVitD: Double, vitDSuggested: Double) -> Bool {
Also in this function, we could remove vitDSuggested from the parameters of the function and use self inside the function body

2023-05-25 14:15 UTC, palant-dev commented on RayD/VitDTimeTracker.swift
> +        if todayVitD == vitDSuggested {
Here we could use self.vitDSuggested

2023-05-25 14:15 UTC, palant-dev requested changes
Check the comments, maybe we could improve even more the functions. But great job, a lot of stuff!

2023-05-26 08:06 UTC, palant-dev approved these changes
Everything is fine. Good job!

2023-05-26 08:06 UTC, palant-dev approved these changes
Everything is fine. Good job!

2023-05-26 08:43 UTC, merged